# Generated by Django 3.0 on 2019-12-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='anio_lanzamiento',
            field=models.IntegerField(verbose_name='año lanzamiento'),
        ),
    ]
